const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/OS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Users/OS/AppData/Local/ms-playwright/chromium-1194/chrome-win/chrome.exe'});const errors=[],checks=[];const ok=s=>{checks.push(s);console.log('PASS '+s)};try{
const p=await b.newPage({viewport:{width:1180,height:820},hasTouch:true,isMobile:true,deviceScaleFactor:2});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:5173/?test=1');await p.waitForFunction(()=>window.__cookingdual);await p.getByRole('button',{name:'Vào bếp thôi!'}).click();await p.waitForFunction(()=>window.__cookingdual.game.phase==='playing');
await p.evaluate(()=>{const g=window.__cookingdual.game;g.player.hand={kind:'bread',state:'ready'};g.player.facingX=1;g.player.facingZ=0;});await p.keyboard.press('KeyQ');await p.waitForFunction(()=>window.__cookingdual.scene.dynamics.ground.size===1);assert.equal(await p.evaluate(()=>window.__cookingdual.game.player.hand),null);await p.keyboard.press('Space');assert.equal(await p.evaluate(()=>window.__cookingdual.game.player.hand.kind),'bread');ok('Q drops a visible item and Space picks it back up');
await p.keyboard.press('KeyQ');await p.evaluate(()=>window.__cookingdual.game.player.hand={kind:'meat',state:'cooked'});await p.keyboard.press('Space');assert.equal(await p.evaluate(()=>window.__cookingdual.game.player.hand.parts.length),2);assert.equal(await p.evaluate(()=>window.__cookingdual.game.groundItems.length),0);ok('ready ingredient on the floor merges into the unplated meal in hand');
await p.waitForTimeout(120);const button=await p.locator('#throw-touch').boundingBox();await p.mouse.move(button.x+button.width/2,button.y+button.height/2);await p.mouse.down();await p.waitForFunction(()=>window.__cookingdual.scene.dynamics.aimLine.visible);await p.evaluate(()=>window.__cookingdual.clearInput());await p.mouse.up();assert.equal(await p.evaluate(()=>window.__cookingdual.game.projectiles.length),0);assert.ok(await p.evaluate(()=>window.__cookingdual.game.player.hand));assert.equal(await p.locator('#throw-touch').evaluate(e=>e.classList.contains('aiming')),false);ok('interrupted throw gesture cancels without losing or launching the held item');
await p.evaluate(()=>{const {game:g}=window.__cookingdual;g.drop();const s=g.stations.find(s=>s.id==='pan-a');g.player.x=s.x;g.player.z=s.z-1.1;g.player.facingX=0;g.player.facingZ=1;s.item.food={kind:'meat',state:'cooked'};s.item.heat=20.95;});await p.waitForFunction(()=>window.__cookingdual.scene.dynamics.fires.size>0);await p.evaluate(()=>{const g=window.__cookingdual.game;g.stations.find(s=>s.id==='pan-a').fireClock=5.95;});await p.waitForFunction(()=>window.__cookingdual.scene.dynamics.fires.size>=3);await p.screenshot({path:'artifacts/fire-spread-ipad.png'});ok('burnt pan produces visible fire that spreads to adjacent boxes');
await p.evaluate(()=>{const g=window.__cookingdual.game,s=g.stations.find(s=>s.id==='extinguisher');g.player.hand=s.item;s.item=null;g.player.z=4.8;});await p.keyboard.down('KeyE');await p.waitForFunction(()=>window.__cookingdual.scene.dynamics.spray.visible);await p.waitForFunction(()=>window.__cookingdual.game.stations.every(s=>!s.fire));await p.keyboard.up('KeyE');ok('holding E sprays extinguisher foam and puts out the burning row');
await p.evaluate(()=>{const g=window.__cookingdual.game;g.drop();const s=g.stations.find(s=>s.id==='pan-a');g.player.x=s.x;g.player.z=s.z-1.1;g.player.facingX=0;g.player.facingZ=1;});await p.keyboard.press('Space');assert.equal(await p.evaluate(()=>window.__cookingdual.game.player.hand.kind),'pan');await p.evaluate(()=>{const g=window.__cookingdual.game,s=g.stations.find(s=>s.id==='trash');g.player.x=s.x;g.player.z=s.z-1.1;g.player.facingX=0;g.player.facingZ=1;});await p.keyboard.press('Space');assert.equal(await p.evaluate(()=>window.__cookingdual.game.player.hand.kind),'pan');assert.equal(await p.evaluate(()=>window.__cookingdual.game.player.hand.food),null);ok('burnt food goes in the trash while the empty reusable pan remains in hand');
await p.locator('#graphics-btn').click();assert.equal(await p.evaluate(()=>window.__cookingdual.game.phase),'paused');await p.locator('#graphics-quality').selectOption('high');assert.equal(await p.evaluate(()=>window.__cookingdual.scene.targetFPS),60);await p.locator('#graphics-quality').selectOption('eco');await p.getByRole('button',{name:'Xong rồi'}).click();assert.equal(await p.evaluate(()=>window.__cookingdual.game.phase),'playing');assert.equal(await p.evaluate(()=>localStorage.getItem('cookingdual-render-quality')),'eco');ok('graphics quality changes FPS, persists, and resumes play after closing');
await p.evaluate(()=>{const g=window.__cookingdual.game;g.reset('playing');g.addOrder();g.addOrder();g.player.facingZ=1;});await p.waitForTimeout(7800);assert.ok(await p.evaluate(()=>{const {game:g,scene:s}=window.__cookingdual;const list=g.orders.map(o=>s.dynamics.customers.get(o.id));return list.length===3&&list.every(c=>c.root.position.distanceTo(c.target)<.06)&&Math.cos(list[0].root.rotation.y)<-.98&&Math.sin(list[1].root.rotation.y)>.8;}));await p.screenshot({path:'artifacts/updated-kitchen-ipad.png'});ok('three customers form an ordered queue; the first faces the cart and followers face the preceding customer');
const oldId=await p.evaluate(()=>{const g=window.__cookingdual.game,id=g.orders[0].id;const plate=g.stations.find(s=>s.id==='plates');plate.item.parts=[{kind:'bread',state:'ready'},{kind:'meat',state:'cooked'},{kind:'vegetable',state:'chopped'}];g.player.hand=plate.item;plate.item=null;const s=g.stations.find(s=>s.id==='serve');g.player.x=s.x;g.player.z=s.z-1.1;g.player.facingZ=1;return id;});await p.keyboard.press('Space');await p.waitForFunction(id=>!window.__cookingdual.scene.dynamics.customers.has(id),oldId);assert.equal(await p.evaluate(()=>window.__cookingdual.game.served),1);ok('serving the matching order makes its customer leave the sidewalk queue');
assert.deepEqual(errors,[]);fs.writeFileSync('artifacts/features-report.json',JSON.stringify({checks,errors},null,2));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
